# Reading List

Each module has an accompanying reading list. Most of the material is optional - either to help further your understanding or provide examples of more advanced applications for those that are interested. It is key that you keep your personal education journey in mind when approaching the optional material. Not all of it may be relevant or necessary for you. Additionally, you will have access to the library system for up to three years after graduating. This means that you can always return to material that becomes more relevant to your next step at a later date.

Most of the readings are articles that are available on Leganto (Imperial's internal reading list system). You will have digital access to all of those articles. Two courses have textbooks that accompany the in class material. These can be borrowed from the school library (subject to availability), purchased, or downloaded as a PDF. A remind that you can download PDF versions of most books for free from the internet in a safe, legal and ethical manner.

[Where to Download PDFs](https://www.pdfreaderpro.com/blog/download-free-pdf-books)


## Statistics

- **Essential Medical Statistics.** Kirkwood B and Sterne J (2003) (2nd ed). Blackwell Science Ltd. [https://www.amazon.co.uk/Essential-Medical-Statistics-Essentials-Kirkwood/dp/0865428719](https://www.amazon.co.uk/Essential-Medical-Statistics-Essentials-Kirkwood/dp/0865428719) 
Chapters 2–5 will support what you learn in the term 1 statistics module.
- **An Introduction to Medical Statistics.** Bland M (2015) (4th ed). Oxford University Press. An alternative excellent standard text book. This includes multiple choice and other questions at the end of chapters, which may be useful for revision purposes. [http://www-users.york.ac.uk/~mb55/intro/introcon.htm](http://www-users.york.ac.uk/~mb55/intro/introcon.htm) (accessed 25 July 2017) contains useful additional material. Chapters 4–7 will support what you learn in the term 1 statistics module.


## Programming

There are no accompanying programming textbooks for HDA. For those interested in having a textbook, the following are free PDFs to download which contain material covering most of the key programming concepts.

[Hands-on programming with R, Garrett Grolemun](https://rstudio-education.github.io/hopr/index.html)

[Intro to Python Programming](https://assets.openstax.org/oscms-prodcms/media/documents/Introduction_to_Python_Programming_-_WEB.pdf)

Note: HDA does not cover recursion as it is more relevant to computer science than large scale data analysis.

[SQL](https://books.goalkicker.com/SQLBook/)



## Epidemiology


**Basic Epidemiology** Bonita et al. Available free of charge from: [https://apps.who.int/iris/bitstream/handle/10665/43541/9241547073_eng.pdf?sequence=1](https://apps.who.int/iris/bitstream/handle/10665/43541/9241547073_eng.pdf?sequence=1)


#### Recommended reading

These books are not covered in the course but have been supplied in the reading list by the module team for those interested in Epidemiology.

- **Oxford Handbook of Epidemiology for Clinicians.** Ward et al. [https://oxfordmedicine.com/view/10.1093/med/9780198529880.001.0001/med-9780198529880](https://oxfordmedicine.com/view/10.1093/med/9780198529880.001.0001/med-9780198529880)

- **Epidemiology(Fifth edition.).** Szklo, M. and Nieto, F.J. (2014).  Burlington, Massachusetts,Jones & Bartlett Learning (approx. £93). Available to purchase from: [https://blackwells.co.uk/bookshop/product/9781449604691?gclid=Cj0KCQjwwqXMBRCDARIsAD-AQ2g9wGEkLUMAkkoIY_FO62AVEVFj2neeE93lnZKq--zCsJF7IuAp65kaAgAKEALw_wcB](https://blackwells.co.uk/bookshop/product/9781449604691?gclid=Cj0KCQjwwqXMBRCDARIsAD-AQ2g9wGEkLUMAkkoIY_FO62AVEVFj2neeE93lnZKq--zCsJF7IuAp65kaAgAKEALw_wcB)
- **Gordis Epidemiology.** Gordis, L. (2014).  Philadelphia, PA: Elsevier Saunders (approx. £35). Available to purchase from: [https://www.uk.elsevierhealth.com/epidemiology-9781455737338.html](https://www.uk.elsevierhealth.com/epidemiology-9781455737338.html)
- **Epidemiology: Beyond the Basics.** Ward H, Toledano M, Shaddick G, Davies B, Elliott P (2012) . Oxford University Press, Oxford UK. (Amazon price £26).
- **Essential epidemiology: an introduction for students and health professionals.** Webb, P., Bain, C. and Page, A., 2016. . Cambridge University Press. [https://www.amazon.co.uk/Essential-Epidemiology-Introduction-Students-Professionals/dp/0521177316](https://www.amazon.co.uk/Essential-Epidemiology-Introduction-Students-Professionals/dp/0521177316)






