# FAQ

HDA has put together an FAQ to address questions students commonly have. Please reach out to one of the HDA staff members if you have a query that is not addressed in this section. [HDA Contact Information](#contact-info)

## 1. Do you have any suggestions for finding accommodation in London? 

When searching for accommodation, take note of the campus where most of your classes will be delivered.  The MSc Health Data Analytics and Machine Learning course is based at the White City Campus in West London. However, some of your classes might take place at the Charing Cross Campus in Hammersmith and in the South Kensington Campus but the majority will be held at White City in the School of Public Health.

For additional information on accommodation, visit the [Imperial College Accommodation website.](https://www.imperial.ac.uk/students/accommodation/)

## 2. How much money will I need to live and study in London for a year?

Please visit the Imperial [Living in London](https://www.imperial.ac.uk/study/living-in-london/) website for detailed information. 

You will need to travel between campuses by bus, bicycle or underground train. Some journeys may be convenient on foot.

## 3. What is my tuition fee status? 

Please visit the Imperial [Fees and Funding](https://www.imperial.ac.uk/study/fees-and-funding/tuition-fees/fee-status/) website for the most up to date information on tuition fees.

## 4. How and when should I send official documents (e.g. degree certificates)?  

Official documents need to be sent to [Registry](https://www.imperial.ac.uk/admin-services/registry/) as soon as they are requested . Please check [My Imperial](https://www.imperial.ac.uk/admin-services/ict/self-service/admin-systems/my-imperial/) portal for instructions on how to send these. All outstanding conditions of your offer will have to be met before you can be offered an unconditional place and register as a student. Registering as a student is a pre-requisite for joining the course. For any questions regarding your documents and outstanding conditions, you can contact Registry directly

## 5. When does the course start?

The MSc Health Data Analytics and Machine Learning Course starts on 30th of September 2024. Further details of the first week of term (i.e. ‘Induction Week’) will be sent via email. 

For international students, Imperial College London organises some orientation events prior to the official start of the course. Please visit the [International Students Webpages](https://www.imperial.ac.uk/study/international-students/)  for further information. 

## 6. I’m an international student – what else should I consider or do before my arrival? 

Please bear in mind that you may need a visa and vaccinations before your arrival.
If you think you will not be able to obtain the visa in time for the start of the course please contact the Postgraduate Education Coordinator, Jo Tite: j.tite at imperial.ac.uk

You may also want to familiarise yourself with information on how to open a bank account, and how to find a general medical practitioner (GP) after your arrival.  Options for GP services include the [Imperial College Health Centre](https://www.imperialcollegehealthcentre.co.uk/) in South Kensington or other services closer to your chosen accommodation.  

Please also make active use of the [general information](https://www.imperial.ac.uk/study/international-students/) resources for international students at Imperial. 

## 7. Where does teaching take place? 

Teaching takes place most at the White City Campus in the School of Public Health. Occasionally you might have some classes in South Kensington and in Hammersmith. This will depend on the modules taken.

Please familiarise yourself with Imperial [campuses and maps](https://www.imperial.ac.uk/visit/campuses/)  

Note: The name of the campus may not correspond to the name of the nearest Underground station. For example, the Charing Cross campus is not near the Charing Cross tube station (but is between Hammersmith and Baron’s Court stations), and the Hammersmith campus is not near Hammersmith station. 

## 8. Do you have a reading list of books to prepare for the course?

We encourage you to do some general preparatory reading; we have attached a list of key texts. However, we do not anticipate prior learning in the subject matters, and the modules are taught starting from a basic level – so there will be adequate opportunities to learn the subjects even if you have never taken these modules beforehand. During term time, you would need to dedicate the allotted time for independent study as well as actively attend the live sessions and lectures.

## 9. Is there other preparation that I should do before starting the course?

You will be required to use software to prepare written reports and prepare slides to accompany presentations. Our computer facilities (see below) offer you access to Microsoft Excel, PowerPoint and Word for this purpose. If you are not familiar with these programmes, you might want to familiarise yourself with them before the course commences. Other software such as R for statistical analysis will be taught on the Course (please see the accompanying R preparation guide). In addition, communication and teaching software such as padlet will be introduced in induction week.


## 10. Will I need to buy a calculator?

You will need to do calculations for practicals and homework, where you can use laptops and/or mobile phones, so it may not be necessary to buy a calculator.

If you decide to buy a calculator, we recommend that you use the CASIO fx-85GT Plus (£9-10). However, any standard scientific calculator should also be fine, so if you already have one, there is no need to buy another one. Importantly, you should check that the calculator has functions to calculate log (bases 2 and 10), exponentials, arithmetic means, standard deviations (S.D.), variance, geometric means, and square roots. We advise that you become familiar with these basic functions of your calculator before your arrival.  

## 11. What books do I need to buy for the course? 

There is a core reading list of texts in addition to the books recommended for your pre-sessional reading. You will receive a handbook containing links to the core reading lists, when you arrive. These key texts will be available in the library (and mostly online), so choosing to buy any of the books will be up to you in case you want to retain a personal copy.  

## 12. Do I need to choose my own summer project topic? 

The summer months in Term 3 are dedicated to full-time work on a research project. We provide students with a list of potential summer project topics at the start of Term 2 (in January), and advise that you start thinking about possible projects before this. Alternatively, you may wish to submit your own project ideas for approval. Your idea for a summer project, must be supported by a member of staff within the School of Public Health who is also willing to supervise the project. If you already have project ideas in mind, please discuss these with your personal tutor or the course organisers soon after your arrival. 

## 13. Who should I contact if I have any further questions? 

If you have any further questions, please consult the following key contacts or resources:

*	The [Registry](https://www.imperial.ac.uk/admin-services/registry/) team for queries on your application, outstanding conditions, fee status, and registration status.
*	Postgraduate Education Co-ordinator, [Ms Jo Tite](https://www.imperial.ac.uk/people/j.tite) (email: j.tite at imperial.ac.uk), for queries on timetables, induction week or any other administrative issues
*	MSc HDA-ML Course Co-lead and organiser for queries on the course content, [Dr Sabrina Rodrigues](https://www.imperial.ac.uk/people/s.andrade-rodrigues) (email: s.andrade-rodrigues at imperial.ac.uk) 
*	Please familiarise yourself with information about postgraduate studies, and further information collated for new postgraduate students before you arrive. 
